# Site settings
title: Daniel | Coder
email: daniel.y.woo@gmail.com
description: 未经允许, 不得转载.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://danielw.cn" # the base hostname & protocol for your site
twitter_username: danielywoo
github_username:  danielywoo

# Build settings
markdown: kramdown
permalink: "/:title"
google_analytics: "UA-67268519-1"
show_downloads: false
theme: jekyll-theme-tactile
